// src/services/storageService.ts
import { auth, storage } from '../lib/firebaseConfig';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'firebase/storage';

const isBrowserStorageAvailable = () => typeof window !== 'undefined' && typeof window.localStorage !== 'undefined';

const getStorageCacheKey = () => {
  const uid = auth.currentUser?.uid || 'anonymous';
  return `smart-school-saas:storage-cache:v1:${uid}`;
};

const loadStorageCache = (): Record<string, string> => {
  if (!isBrowserStorageAvailable()) return {};
  try {
    const raw = window.localStorage.getItem(getStorageCacheKey());
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
};

const saveStorageCache = (cache: Record<string, string>): void => {
  if (!isBrowserStorageAvailable()) return;
  try {
    window.localStorage.setItem(getStorageCacheKey(), JSON.stringify(cache));
  } catch {
    // Ignore storage write errors (e.g. quota exceeded)
  }
};

const cacheDataUrl = (path: string, dataUrl: string): void => {
  const cache = loadStorageCache();
  cache[path] = dataUrl;
  saveStorageCache(cache);
};

const removeCachedDataUrl = (path: string): void => {
  const cache = loadStorageCache();
  delete cache[path];
  saveStorageCache(cache);
};

const blobToDataUrl = (blob: Blob): Promise<string> => new Promise((resolve, reject) => {
  const reader = new FileReader();
  reader.onload = () => {
    if (typeof reader.result === 'string') {
      resolve(reader.result);
      return;
    }
    reject(new Error('Could not convert file to a data URL.'));
  };
  reader.onerror = () => reject(new Error('Could not convert file to a data URL.'));
  reader.readAsDataURL(blob);
});

export const storageService = {
  /**
   * Uploads a raw File or Blob object to Firebase Storage and returns its public download URL.
   * @param path The storage path (e.g. 'schools/vanguard/logo.png')
   * @param file The file or blob to upload
   */
  uploadFile: async (path: string, file: File | Blob): Promise<string> => {
    try {
      const storageRef = ref(storage, path);
      await uploadBytes(storageRef, file);
      const url = await getDownloadURL(storageRef);
      return url;
    } catch (err) {
      console.warn("Firebase Storage upload failed, falling back to a local data URL cache:", err);
      const dataUrl = await blobToDataUrl(file);
      cacheDataUrl(path, dataUrl);
      return dataUrl;
    }
  },

  /**
   * Converts a Base64 data URI string to a standard Blob object.
   */
  base64ToBlob: (base64Data: string): Blob => {
    const arr = base64Data.split(',');
    const mime = arr[0].match(/:(.*?);/)?.[1] || 'image/png';
    const bstr = atob(arr[1]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new Blob([u8arr], { type: mime });
  },

  /**
   * Safe wrapper that uploads a base64 image string (Data URI) to Firebase Storage.
   * If the input is already a standard URL, it bypasses the upload and returns it directly.
   * @param path Target storage path
   * @param base64Data Base64 Data URI string or already-existing URL
   */
  uploadBase64Image: async (path: string, base64Data: string): Promise<string> => {
    if (!base64Data || !base64Data.startsWith('data:')) {
      return base64Data; // Already a URL, bypass upload
    }
    try {
      const blob = storageService.base64ToBlob(base64Data);
      return await storageService.uploadFile(path, blob);
    } catch (err) {
      console.error("Base64 upload failed for path:", path, err);
      return base64Data; // Fallback to raw base64 to avoid data loss
    }
  },

  /**
   * Deletes a file from Firebase Storage if it exists.
   */
  deleteFile: async (path: string): Promise<void> => {
    try {
      const storageRef = ref(storage, path);
      await deleteObject(storageRef);
    } catch (err) {
      console.warn("Could not delete storage file:", err);
    }
    removeCachedDataUrl(path);
  },

  /**
   * Reads a cached data URL from local browser storage when Firebase Storage is unavailable.
   */
  getCachedDataUrl: (path: string): string | null => {
    const cache = loadStorageCache();
    return cache[path] || null;
  },

  /**
   * Dynamically constructs the optimized thumbnail URL (200x200 or 500x500 WebP)
   * generated by the firebase/storage-resize-images extension.
   * If the input URL is not a standard Cloud Storage URL, it returns it unchanged.
   */
  getThumbnailUrl: (url: string | null | undefined, size: '200x200' | '500x500' = '200x200'): string => {
    if (!url) return '';
    if (!url.includes('firebasestorage.googleapis.com')) return url;

    try {
      // Extract the base URL and query parameters
      const parts = url.split('?');
      const baseUrl = parts[0];
      const queryParams = parts[1] ? `?${parts[1]}` : '';

      // Get the encoded storage path
      const oMatch = baseUrl.split('/o/');
      if (oMatch.length < 2) return url;
      const pathSegment = oMatch[1];

      // Decode path, swap the extension and append the size suffix, then re-encode
      const decodedPath = decodeURIComponent(pathSegment);
      const dotIndex = decodedPath.lastIndexOf('.');
      if (dotIndex === -1) return url;

      const baseName = decodedPath.substring(0, dotIndex);
      // Resized images are named as: [name]_[size].[type]
      const thumbPath = `${baseName}_${size}.webp`;
      const encodedThumbPath = encodeURIComponent(thumbPath);

      return `${oMatch[0]}/o/${encodedThumbPath}${queryParams}`;
    } catch (err) {
      console.warn("Could not generate thumbnail URL:", err);
      return url;
    }
  }
};
