// src/services/storageService.ts
import { storage } from '../lib/firebaseConfig';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'firebase/storage';

export const storageService = {
  /**
   * Uploads a raw File or Blob object to Firebase Storage and returns its public download URL.
   * @param path The storage path (e.g. 'schools/vanguard/logo.png')
   * @param file The file or blob to upload
   */
  uploadFile: async (path: string, file: File | Blob): Promise<string> => {
    const storageRef = ref(storage, path);
    await uploadBytes(storageRef, file);
    return getDownloadURL(storageRef);
  },

  /**
   * Converts a Base64 data URI string to a standard Blob object.
   */
  base64ToBlob: (base64Data: string): Blob => {
    const arr = base64Data.split(',');
    const mime = arr[0].match(/:(.*?);/)?.[1] || 'image/png';
    const bstr = atob(arr[1]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new Blob([u8arr], { type: mime });
  },

  /**
   * Safe wrapper that uploads a base64 image string (Data URI) to Firebase Storage.
   * If the input is already a standard URL, it bypasses the upload and returns it directly.
   * @param path Target storage path
   * @param base64Data Base64 Data URI string or already-existing URL
   */
  uploadBase64Image: async (path: string, base64Data: string): Promise<string> => {
    if (!base64Data || !base64Data.startsWith('data:')) {
      return base64Data; // Already a URL, bypass upload
    }
    try {
      const blob = storageService.base64ToBlob(base64Data);
      return await storageService.uploadFile(path, blob);
    } catch (err) {
      console.error("Base64 upload failed for path:", path, err);
      return base64Data; // Fallback to raw base64 to avoid data loss
    }
  },

  /**
   * Deletes a file from Firebase Storage if it exists.
   */
  deleteFile: async (path: string): Promise<void> => {
    try {
      const storageRef = ref(storage, path);
      await deleteObject(storageRef);
    } catch (err) {
      console.warn("Could not delete storage file:", err);
    }
  },

  /**
   * Dynamically constructs the optimized thumbnail URL (200x200 or 500x500 WebP)
   * generated by the firebase/storage-resize-images extension.
   * If the input URL is not a standard Cloud Storage URL, it returns it unchanged.
   */
  getThumbnailUrl: (url: string | null | undefined, size: '200x200' | '500x500' = '200x200'): string => {
    if (!url) return '';
    if (!url.includes('firebasestorage.googleapis.com')) return url;

    try {
      // Extract the base URL and query parameters
      const parts = url.split('?');
      const baseUrl = parts[0];
      const queryParams = parts[1] ? `?${parts[1]}` : '';

      // Get the encoded storage path
      const oMatch = baseUrl.split('/o/');
      if (oMatch.length < 2) return url;
      const pathSegment = oMatch[1];

      // Decode path, swap the extension and append the size suffix, then re-encode
      const decodedPath = decodeURIComponent(pathSegment);
      const dotIndex = decodedPath.lastIndexOf('.');
      if (dotIndex === -1) return url;

      const baseName = decodedPath.substring(0, dotIndex);
      // Resized images are named as: [name]_[size].[type]
      const thumbPath = `${baseName}_${size}.webp`;
      const encodedThumbPath = encodeURIComponent(thumbPath);

      return `${oMatch[0]}/o/${encodedThumbPath}${queryParams}`;
    } catch (err) {
      console.warn("Could not generate thumbnail URL:", err);
      return url;
    }
  }
};
